version: "3.8"
services:
  nestapp:
    container_name: nestapp
    image: tu9l3/nestapp:1.0.0
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - 3000:3000
    environment:
      - DB_TYPE=postgres
      - DB_HOST=db
      - DB_USERNAME=postgres
      - DB_PASSWORD=12345
      - DB_DATABASE=postgres
      - DB_PORT=5432
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}